version: '3.8'

services:
  url-shortener:
      build: .
      image: url-shortener:latest
      container_name: url-shortener
      ports:
        - '3000:3000'
      restart: unless-stopped
      environment:
        - MONGODB=mongodb://root:root@mongodb:27017/urlshortener?authSource=admin
        - REDIS_HOST=redis

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=urlshortener
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  redis:
    container_name: redis
    image: redis
